# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: serve

  install-mdbook:
    status:
      - ! command -v mdbook
      - ! command -v mdbook-last-changed
      - ! command -v mdbook-mermaid
    preconditions:
      - sh: command -v cargo
        msg: The Rust toolchain (cargo) needs to be installed to install mdbook
    cmds:
      - cargo install mdbook mdbook-last-changed mdbook-mermaid

  serve:
    deps:
      - install-mdbook
    cmds:
      - mdbook serve -o
